apiVersion: v1
kind: Service
metdata:
  name: redis
  Labels:
    name: redis-service
    app: demo-voting-app
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis-service
    app: demo-voting-app
