apiVersion: v1
kind: Service
metdata:
  name: voting-service
  Labels:
    name: redis-service
    app: demo-voting-app
spec:
  type:  Loadbalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: voting-app-pod
    app: demo-voting-app
